
package ass8;

import schema.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InfoManagementInterface", targetNamespace = "http://jw.nju.edu.cn/ass7")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InfoManagementInterface {


    /**
     *
     * @param studentId
     * @return
     *     returns wsdl2.学生信息类型
     * @throws InvalidDataFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/ass7/getInfoById")
    @WebResult(name = "student", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "student")
    public 学生信息类型 getInfoById(
            @WebParam(name = "studentId", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "studentId")
                    String studentId)
        throws InvalidDataFault
    ;

    /**
     *
     * @param studentName
     * @return
     *     returns wsdl2.学生列表类型
     * @throws InvalidDataFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/ass7/getInfoByName")
    @WebResult(name = "studentList", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "students")
    public 学生列表类型 getInfoByName(
            @WebParam(name = "studentName", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "studentName")
                    String studentName)
        throws InvalidDataFault
    ;

    /**
     *
     * @param student
     * @return
     *     returns java.lang.String
     * @throws InvalidDataFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/ass7/modifyInfo")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "isSuccess")
    public String modifyInfo(
            @WebParam(name = "student", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "student")
                    学生信息类型 student)
        throws InvalidDataFault
    ;

    /**
     *
     * @param student
     * @return
     *     returns java.lang.String
     * @throws InvalidDataFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/ass7/addInfo")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "isSuccess")
    public String addInfo(
            @WebParam(name = "student", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "student")
                    学生信息类型 student)
        throws InvalidDataFault
    ;

    /**
     *
     * @param studentId
     * @return
     *     returns java.lang.String
     * @throws InvalidDataFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/ass7/deleteInfo")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "isSuccess")
    public String deleteInfo(
            @WebParam(name = "studentId", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "studentId")
                    String studentId)
        throws InvalidDataFault
    ;

}
