
package ass8;


import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InfoManagementService", targetNamespace = "http://jw.nju.edu.cn/ass7", wsdlLocation = "file:/D:/workspace/SOA/ServerSide2/web/ass7/InfoManagementService.ass7")
public class InfoManagementService
    extends Service
{

    private final static URL INFOMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException INFOMANAGEMENTSERVICE_EXCEPTION;
    private final static QName INFOMANAGEMENTSERVICE_QNAME = new QName("http://jw.nju.edu.cn/ass7", "InfoManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace/SOA/ServerSide2/web/ass7/InfoManagementService.ass7");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INFOMANAGEMENTSERVICE_WSDL_LOCATION = url;
        INFOMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public InfoManagementService() {
        super(__getWsdlLocation(), INFOMANAGEMENTSERVICE_QNAME);
    }

    public InfoManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INFOMANAGEMENTSERVICE_QNAME, features);
    }

    public InfoManagementService(URL wsdlLocation) {
        super(wsdlLocation, INFOMANAGEMENTSERVICE_QNAME);
    }

    public InfoManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INFOMANAGEMENTSERVICE_QNAME, features);
    }

    public InfoManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfoManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InfoManagementInterface
     */
    @WebEndpoint(name = "InfoPort")
    public InfoManagementInterface getInfoPort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/ass7", "InfoPort"), InfoManagementInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoManagementInterface
     */
    @WebEndpoint(name = "InfoPort")
    public InfoManagementInterface getInfoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/ass7", "InfoPort"), InfoManagementInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INFOMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw INFOMANAGEMENTSERVICE_EXCEPTION;
        }
        return INFOMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
