
package ass8;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VerificationService", targetNamespace = "http://jw.nju.edu.cn/ass7", wsdlLocation = "file:/D:/workspace/SOA/ServerSide2/web/ass7/Verification.ass7")
public class VerificationService
    extends Service
{

    private final static URL VERIFICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException VERIFICATIONSERVICE_EXCEPTION;
    private final static QName VERIFICATIONSERVICE_QNAME = new QName("http://jw.nju.edu.cn/ass7", "VerificationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace/SOA/ServerSide2/web/ass7/Verification.ass7");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERIFICATIONSERVICE_WSDL_LOCATION = url;
        VERIFICATIONSERVICE_EXCEPTION = e;
    }

    public VerificationService() {
        super(__getWsdlLocation(), VERIFICATIONSERVICE_QNAME);
    }

    public VerificationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERIFICATIONSERVICE_QNAME, features);
    }

    public VerificationService(URL wsdlLocation) {
        super(wsdlLocation, VERIFICATIONSERVICE_QNAME);
    }

    public VerificationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERIFICATIONSERVICE_QNAME, features);
    }

    public VerificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerificationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VerificationInterface
     */
    @WebEndpoint(name = "verifyPort")
    public VerificationInterface getVerifyPort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/ass7", "verifyPort"), VerificationInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerificationInterface
     */
    @WebEndpoint(name = "verifyPort")
    public VerificationInterface getVerifyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/ass7", "verifyPort"), VerificationInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERIFICATIONSERVICE_EXCEPTION!= null) {
            throw VERIFICATIONSERVICE_EXCEPTION;
        }
        return VERIFICATIONSERVICE_WSDL_LOCATION;
    }

}
