
package ass8;

import schema.验证信息类型;
import schema.验证结果类型;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "verificationInterface", targetNamespace = "http://jw.nju.edu.cn/ass7")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VerificationInterface {


    /**
     * 
     * @param verityInfo
     * @return
     *     returns schema.验证结果类型
     * @throws InvalidDataFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/ass7/verify")
    @WebResult(name = "VerifyMsg", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "verifyMsg")
    public 验证结果类型 verify(
        @WebParam(name = "verifyInfo", targetNamespace = "http://jw.nju.edu.cn/ass7", partName = "verityInfo")
                验证信息类型 verityInfo)
        throws InvalidDataFault
    ;

}
