
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScoreService", targetNamespace = "http://jw.nju.edu.cn/wsdl", wsdlLocation = "file:/D:/workspace/SOA/ServerSide2/src/schema/score-manage.wsdl")
public class ScoreService
    extends Service
{

    private final static URL SCORESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCORESERVICE_EXCEPTION;
    private final static QName SCORESERVICE_QNAME = new QName("http://jw.nju.edu.cn/wsdl", "ScoreService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace/SOA/ServerSide2/src/schema/score-manage.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCORESERVICE_WSDL_LOCATION = url;
        SCORESERVICE_EXCEPTION = e;
    }

    public ScoreService() {
        super(__getWsdlLocation(), SCORESERVICE_QNAME);
    }

    public ScoreService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCORESERVICE_QNAME, features);
    }

    public ScoreService(URL wsdlLocation) {
        super(wsdlLocation, SCORESERVICE_QNAME);
    }

    public ScoreService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCORESERVICE_QNAME, features);
    }

    public ScoreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StuScoreInterface
     */
    @WebEndpoint(name = "ScorePort")
    public StuScoreInterface getScorePort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "ScorePort"), StuScoreInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StuScoreInterface
     */
    @WebEndpoint(name = "ScorePort")
    public StuScoreInterface getScorePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "ScorePort"), StuScoreInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCORESERVICE_EXCEPTION!= null) {
            throw SCORESERVICE_EXCEPTION;
        }
        return SCORESERVICE_WSDL_LOCATION;
    }

}
