
package ass7;

import schema.删除成绩数据类型;
import schema.单个学生成绩列表类型;
import schema.添加或修改成绩数据类型;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "stuScoreInterface", targetNamespace = "http://jw.nju.edu.cn/test1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StuScoreInterface {


    /**
     * 
     * @param studentId
     * @return
     *     returns schema.单个学生成绩列表类型
     * @throws SearchScoreFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/test1/searchScore")
    @WebResult(name = "studentScore", targetNamespace = "http://jw.nju.edu.cn/test1", partName = "scoreList")
    public 单个学生成绩列表类型 searchScore(
        @WebParam(name = "studentId", targetNamespace = "http://jw.nju.edu.cn/test1", partName = "studentId")
        String studentId)
        throws SearchScoreFault
    ;

    /**
     * 
     * @param student
     * @return
     *     returns java.lang.String
     * @throws AddScoreFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/test1/addScore")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/test1", partName = "isSuccess")
    public String addScore(
        @WebParam(name = "addScore", targetNamespace = "http://jw.nju.edu.cn/test1", partName = "student")
        添加或修改成绩数据类型 student)
        throws AddScoreFault
    ;

    /**
     * 
     * @param student
     * @return
     *     returns java.lang.String
     * @throws DeleteScoreFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/test1/deleteScore")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/test1", partName = "isSuccess")
    public String deleteScore(
        @WebParam(name = "deleteScore", targetNamespace = "http://jw.nju.edu.cn/test1", partName = "student")
                删除成绩数据类型 student)
        throws DeleteScoreFault
    ;

    /**
     * 
     * @param student
     * @return
     *     returns java.lang.String
     * @throws ModifyScoreFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/test1/modifyScore")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/test1", partName = "isSuccess")
    public String modifyScore(
        @WebParam(name = "modifyScore", targetNamespace = "http://jw.nju.edu.cn/test1", partName = "student")
                添加或修改成绩数据类型 student)
        throws ModifyScoreFault
    ;


}
