
package services.score;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScoreControllerService", targetNamespace = "http://jw.nju.edu.cn/schema", wsdlLocation = "http://106.15.183.234:8080/soap-api/score?wsdl")
//@HandlerChain(file="default-handler-chain.xml")
public class ScoreControllerService
    extends Service
{

    private final static URL SCORECONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCORECONTROLLERSERVICE_EXCEPTION;
    private final static QName SCORECONTROLLERSERVICE_QNAME = new QName("http://jw.nju.edu.cn/schema", "ScoreControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://106.15.183.234:8080/soap-api/score?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCORECONTROLLERSERVICE_WSDL_LOCATION = url;
        SCORECONTROLLERSERVICE_EXCEPTION = e;
    }

    public ScoreControllerService() {
        super(__getWsdlLocation(), SCORECONTROLLERSERVICE_QNAME);
    }

    public ScoreControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCORECONTROLLERSERVICE_QNAME, features);
    }

    public ScoreControllerService(URL wsdlLocation) {
        super(wsdlLocation, SCORECONTROLLERSERVICE_QNAME);
    }

    public ScoreControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCORECONTROLLERSERVICE_QNAME, features);
    }

    public ScoreControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Score
     */
    @WebEndpoint(name = "ScorePort")
    public Score getScorePort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/schema", "ScorePort"), Score.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Score
     */
    @WebEndpoint(name = "ScorePort")
    public Score getScorePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/schema", "ScorePort"), Score.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCORECONTROLLERSERVICE_EXCEPTION!= null) {
            throw SCORECONTROLLERSERVICE_EXCEPTION;
        }
        return SCORECONTROLLERSERVICE_WSDL_LOCATION;
    }

}
