
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StuScoreImplService", targetNamespace = "http://wsdl/", wsdlLocation = "http://localhost:8888/ns?wsdl")
public class StuScoreImplService
    extends Service
{

    private final static URL STUSCOREIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUSCOREIMPLSERVICE_EXCEPTION;
    private final static QName STUSCOREIMPLSERVICE_QNAME = new QName("http://wsdl/", "StuScoreImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ns?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUSCOREIMPLSERVICE_WSDL_LOCATION = url;
        STUSCOREIMPLSERVICE_EXCEPTION = e;
    }

    public StuScoreImplService() {
        super(__getWsdlLocation(), STUSCOREIMPLSERVICE_QNAME);
    }

    public StuScoreImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUSCOREIMPLSERVICE_QNAME, features);
    }

    public StuScoreImplService(URL wsdlLocation) {
        super(wsdlLocation, STUSCOREIMPLSERVICE_QNAME);
    }

    public StuScoreImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUSCOREIMPLSERVICE_QNAME, features);
    }

    public StuScoreImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StuScoreImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StuScoreImpl
     */
    @WebEndpoint(name = "StuScoreImplPort")
    public StuScoreImpl getStuScoreImplPort() {
        return super.getPort(new QName("http://wsdl/", "StuScoreImplPort"), StuScoreImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StuScoreImpl
     */
    @WebEndpoint(name = "StuScoreImplPort")
    public StuScoreImpl getStuScoreImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsdl/", "StuScoreImplPort"), StuScoreImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUSCOREIMPLSERVICE_EXCEPTION!= null) {
            throw STUSCOREIMPLSERVICE_EXCEPTION;
        }
        return STUSCOREIMPLSERVICE_WSDL_LOCATION;
    }

}
