
package wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StuScoreImpl", targetNamespace = "http://wsdl/")
@XmlSeeAlso({
    cn.edu.nju.jw.wsdl.ObjectFactory.class,
    ObjectFactory.class
})
public interface StuScoreImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ModifyScoreFault
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyScore", targetNamespace = "http://wsdl/", className = "wsdl.ModifyScore")
    @ResponseWrapper(localName = "modifyScoreResponse", targetNamespace = "http://wsdl/", className = "wsdl.ModifyScoreResponse")
    @Action(input = "http://wsdl/StuScoreImpl/modifyScoreRequest", output = "http://wsdl/StuScoreImpl/modifyScoreResponse", fault = {
        @FaultAction(className = ModifyScoreFault.class, value = "http://wsdl/StuScoreImpl/modifyScore/Fault/ModifyScoreFault")
    })
    public String modifyScore(
            @WebParam(name = "arg0", targetNamespace = "")
                    添加或修改成绩类型 arg0)
        throws ModifyScoreFault
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns wsdl.单个学生成绩列表类型
     * @throws SearchScoreFault
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchScore", targetNamespace = "http://wsdl/", className = "wsdl.SearchScore")
    @ResponseWrapper(localName = "searchScoreResponse", targetNamespace = "http://wsdl/", className = "wsdl.SearchScoreResponse")
    @Action(input = "http://wsdl/StuScoreImpl/searchScoreRequest", output = "http://wsdl/StuScoreImpl/searchScoreResponse", fault = {
        @FaultAction(className = SearchScoreFault.class, value = "http://wsdl/StuScoreImpl/searchScore/Fault/SearchScoreFault")
    })
    public 单个学生成绩列表类型 searchScore(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0)
        throws SearchScoreFault
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws DeleteScoreFault
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteScore", targetNamespace = "http://wsdl/", className = "wsdl.DeleteScore")
    @ResponseWrapper(localName = "deleteScoreResponse", targetNamespace = "http://wsdl/", className = "wsdl.DeleteScoreResponse")
    @Action(input = "http://wsdl/StuScoreImpl/deleteScoreRequest", output = "http://wsdl/StuScoreImpl/deleteScoreResponse", fault = {
        @FaultAction(className = DeleteScoreFault.class, value = "http://wsdl/StuScoreImpl/deleteScore/Fault/DeleteScoreFault")
    })
    public String deleteScore(
            @WebParam(name = "arg0", targetNamespace = "")
                    删除成绩类型 arg0)
        throws DeleteScoreFault
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws AddScoreFault
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addScore", targetNamespace = "http://wsdl/", className = "wsdl.AddScore")
    @ResponseWrapper(localName = "addScoreResponse", targetNamespace = "http://wsdl/", className = "wsdl.AddScoreResponse")
    @Action(input = "http://wsdl/StuScoreImpl/addScoreRequest", output = "http://wsdl/StuScoreImpl/addScoreResponse", fault = {
        @FaultAction(className = AddScoreFault.class, value = "http://wsdl/StuScoreImpl/addScore/Fault/AddScoreFault")
    })
    public String addScore(
            @WebParam(name = "arg0", targetNamespace = "")
                    添加或修改成绩类型 arg0)
        throws AddScoreFault
    ;

}
