
package cn.edu.nju;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "service.LoginPort", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceLoginPort {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service/", className = "cn.edu.nju.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service/", className = "cn.edu.nju.LoginResponse")
    @Action(input = "http://service/service.LoginPort/loginRequest", output = "http://service/service.LoginPort/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
