
package services.info;

import schema.学生类型;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentPort", targetNamespace = "http://jw.nju.edu.cn/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns schema.学生类型
     * @throws AuthorityException
     * @throws IdNotFoundException
     */
    @WebMethod(action = "student/deleteInfoById")
    @WebResult(name = "\u5b66\u751f", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    @Action(input = "student/deleteInfoByIdRequest", output = "student/deleteInfoByIdResponse", fault = {
        @FaultAction(className = AuthorityException.class, value = "student/deleteInfoById/Fault/AuthorityException"),
        @FaultAction(className = IdNotFoundException.class, value = "student/deleteInfoById/Fault/IdNotFoundException")
    })
    public 学生类型 deleteInfoById(
        @WebParam(name = "deleteInfoByIdElement", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
        DeleteInfoByIdType parameters)
        throws AuthorityException, IdNotFoundException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns schema.学生类型
     * @throws IdNotFoundException
     */
    @WebMethod(action = "student/addInfo")
    @WebResult(name = "\u5b66\u751f", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    @Action(input = "student/addInfoRequest", output = "student/addInfoResponse", fault = {
        @FaultAction(className = IdNotFoundException.class, value = "student/addInfo/Fault/AuthorityException")
    })
    public 学生类型 addInfo(
        @WebParam(name = "addInfoElement", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
        AddInfoType parameters)
        throws IdNotFoundException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns schema.学生类型
     * @throws IdNotFoundException
     */
    @WebMethod(action = "student/getInfoById")
    @WebResult(name = "\u5b66\u751f", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    @Action(input = "student/getInfoByIdRequest", output = "student/getInfoByIdResponse", fault = {
        @FaultAction(className = IdNotFoundException.class, value = "student/getInfoById/Fault/IdNotFoundException")
    })
    public 学生类型 getInfoById(
        @WebParam(name = "getInfoByIdElement", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
        GetInfoByIdType parameters)
        throws IdNotFoundException
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns schema.学生类型
     * @throws AuthorityException
     * @throws ScoreTypeException
     * @throws IdNotFoundException
     * @throws ScoreModifyException
     */
    @WebMethod(action = "student/updateInfo")
    @WebResult(name = "\u5b66\u751f", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    @Action(input = "student/updateInfoRequest", output = "student/updateInfoResponse", fault = {
        @FaultAction(className = ScoreTypeException.class, value = "student/updateInfo/Fault/ScoreTypeException"),
        @FaultAction(className = ScoreModifyException.class, value = "student/updateInfo/Fault/ScoreModifyException"),
        @FaultAction(className = AuthorityException.class, value = "student/updateInfo/Fault/AuthorityException"),
        @FaultAction(className = IdNotFoundException.class, value = "student/updateInfo/Fault/IdNotFoundException")
    })
    public 学生类型 updateInfo(
        @WebParam(name = "updateInfoElement", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
                学生类型 parameters)
        throws AuthorityException, IdNotFoundException, ScoreModifyException, ScoreTypeException
    ;

}
