
package services.info;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentControllerService", targetNamespace = "http://jw.nju.edu.cn/schema", wsdlLocation = "http://106.15.183.234:8080/soap-api/student?wsdl")
public class StudentControllerService
    extends Service
{

    private final static URL STUDENTCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTCONTROLLERSERVICE_EXCEPTION;
    private final static QName STUDENTCONTROLLERSERVICE_QNAME = new QName("http://jw.nju.edu.cn/schema", "StudentControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://106.15.183.234:8080/soap-api/student?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTCONTROLLERSERVICE_WSDL_LOCATION = url;
        STUDENTCONTROLLERSERVICE_EXCEPTION = e;
    }

    public StudentControllerService() {
        super(__getWsdlLocation(), STUDENTCONTROLLERSERVICE_QNAME);
    }

    public StudentControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTCONTROLLERSERVICE_QNAME, features);
    }

    public StudentControllerService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTCONTROLLERSERVICE_QNAME);
    }

    public StudentControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTCONTROLLERSERVICE_QNAME, features);
    }

    public StudentControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentPort
     */
    @WebEndpoint(name = "StudentPortPort")
    public StudentPort getStudentPortPort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/schema", "StudentPortPort"), StudentPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentPort
     */
    @WebEndpoint(name = "StudentPortPort")
    public StudentPort getStudentPortPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/schema", "StudentPortPort"), StudentPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTCONTROLLERSERVICE_EXCEPTION!= null) {
            throw STUDENTCONTROLLERSERVICE_EXCEPTION;
        }
        return STUDENTCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
